### ISSUE TITLE
deprecated api

### ISSUE THREAD

**Issue by avalanche1** [JackAdams/constellation-distro#4]
pls fix this warnings in chrome
![image](https://cloud.githubusercontent.com/assets/10534563/10664671/48d53e0e-78d6-11e5-96a3-b9d3e1382cfa.png)

**Comment by JackAdams** [comment]
Is this still coming up on the latest version?

**Comment by avalanche1** [comment]
I use meteor 1.1 and 1.0.7 is the latest version I can install on it. And it gives this warning.

**Comment by JackAdams** [comment]
Those warnings are fixed in the latest version of Constellation but, like you say, one of the packages in `babrahams:constellation` must have a dependency on a 1.2 version of Meteor.  That's unfortunate, as Constellation probably doesn't require 1.2 (or even 1.1).  One way to solve it is to clone the `constellation:console` package into your `.packages` files and edit the `package.js` file so that the `dependsOn` Meteor version is 1.1.  That's a pain to maintain though, I know.

**Comment by avalanche1** [comment]
thanks! though I don't actually realise how to do it... :smile:
